name = "yodelingtornado-site"
compatibility_date = "2026-02-22"

pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"                  # this must match env.DB in your JS
database_name = "yodelingtornado-requests"  # the D1 name you created
database_id = "f6c95b5f-4183-4cbc-8656-a78ade8a935f"